name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: npm install

    - name: Run lint checks
      # Replace 'npm run lint' with your actual lint command
      run: npm run index 

    - name: Run test cases
      # Replace 'npm test' with your actual test command
      run: npm test
